let moviedb = [
  {
    id: 1,
    name: "Ratatouille",
    director: "Kranthi",
    year: 2007,
    genre: "Animation",
    rating: 8.1,
  },
  {
    id: 2,
    name: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
  },
  {
    id: 3,
    name: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: "Action",
    rating: 9.0,
  },
  {
    id: 4,
    name: "Parasite",
    director: "Bong Joon-ho",
    year: 2019,
    genre: "Thriller",
    rating: 8.6,
  },
  {
    id: 5,
    name: "Interstellar",
    director: "Christopher Nolan",
    year: 2014,
    genre: "Adventure",
    rating: 8.6,
  },
  {
    id: 6,
    name: "Whiplash",
    director: "Damien Chazelle",
    year: 2014,
    genre: "Drama",
    rating: 8.5,
  },
  {
    id: 7,
    name: "Spirited Away",
    director: "Hayao Miyazaki",
    year: 2001,
    genre: "Animation",
    rating: 8.6,
  },
  {
    id: 8,
    name: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: "Crime",
    rating: 9.2,
  },
  {
    id: 9,
    name: "Avengers: Endgame",
    director: "Anthony and Joe Russo",
    year: 2019,
    genre: "Action",
    rating: 8.4,
  },
  {
    id: 10,
    name: "Joker",
    director: "Todd Phillips",
    year: 2019,
    genre: "Crime",
    rating: 8.5,
  },
];

export default moviedb;